[general]
name = "regexp"
version = "1.0.0"
description = "Provides regular expression matching."

[build]
files = [
    "regexp.fix",
    "regexp_nfa.fix",
    "regexp_pattern.fix",
    "simple_parser.fix",
    "stringex.fix",
]

[build.test]
files = ["test.fix"]

[[dependencies]]
name = "hashmap"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "character"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-character.git" }
